((id "T11")
 (title "C4 sandboxed executor: racket/sandbox + OS isolation option, structured results")
 (status done)
 (priority 1)
 (goal
  "Foundation for A2/A3 and for hardening `steer api`. Time/memory limits, no network, fs restricted to project (read) + temp (write).")
 (after ())
 (checks ("raco test tests/sandbox-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("tool"))
 (claimed-by "claude")
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-27T19:36:14Z")
 (log
  (((agent "claude")
    (kind note)
    (seq 405)
    (text
     "Promoted to p1: notes/07's T9 baseline run (C0 23%, C1 29%, C2-lite/steer-syntax 23% - zero measured lift from steer's own tool at n=65/28, underpowered but real) found the largest remaining failure class is unbound-identifier resolution, and T13 (A2 binding/arity checker) is the evidence-backed next tool - blocked only on this task. Building more analysis tooling ahead of T11/T13 would repeat the pattern notes/04 warns against (build before measuring).")
    (ts "2026-09-27T19:25:53Z"))
   ((agent "claude")
    (kind note)
    (seq 407)
    (text
     "racket/sandbox's eval-limits are asymmetric, checked directly rather than assumed: a CPU-time violation raises exn:fail:resource (resource='time) synchronously; a memory violation kills the custodian out-of-band and surfaces only as a plain exn:fail 'evaluator: terminated (out-of-memory)'. Also: make-module-evaluator treats a bare string as literal source text, not a file path - must convert with string->path or it reads the path itself as (invalid) source. Both found by probing real behavior before writing classify(), not from docs. Worker runs in the installed racket via subprocess (api.rkt/doc.rkt's pattern), never inside this raco-exe binary, so it needs no OS-isolation escape hatch beyond subprocess-kill for v1.")
    (ts "2026-09-27T19:36:10Z"))
   ((agent "claude")
    (checks (((cmd "raco test tests/sandbox-test.rkt") (secs 3.6))))
    (kind done)
    (seq 408)
    (ts "2026-09-27T19:36:14Z")
    (verified #t)))))
