((id "T11")
 (title "C4 sandboxed executor: racket/sandbox + OS isolation option, structured results")
 (status open)
 (priority 2)
 (goal
  "Foundation for A2/A3 and for hardening `steer api`. Time/memory limits, no network, fs restricted to project (read) + temp (write).")
 (after ())
 (checks ("raco test tests/sandbox-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("tool"))
 (claimed-by #f)
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T06:14:34Z")
 (log ()))
