((id "T12")
 (title "B1 doc and signature lookup: sig/search/exports/exists? from the doc index")
 (status open)
 (priority 1)
 (goal
  "Real signatures instead of remembered ones; cheap exists? check against hallucinated ids. Must work from the standalone binary (shell out like api.rkt if needed).")
 (after ())
 (checks ("raco test tests/doc-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("tool"))
 (claimed-by #f)
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T06:14:34Z")
 (log ()))
