((id "T12")
 (title "B1 doc and signature lookup: sig/search/exports/exists? from the doc index")
 (status done)
 (priority 1)
 (goal
  "Real signatures instead of remembered ones; cheap exists? check against hallucinated ids. Must work from the standalone binary (shell out like api.rkt if needed).")
 (after ())
 (checks ("raco test tests/doc-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("tool"))
 (claimed-by "claude")
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T23:01:24Z")
 (log
  (((agent "claude")
    (kind note)
    (seq 137)
    (text
     "Built steer/doc.rkt (exists/sig/search/exports), worker in installed racket. exists warns not-in-racket for names only in srfi/teaching languages. Suggestions: phrase synonyms + verb-token ranking + edit distance over racket/* names. Held-out fresh2: top-1 4 -> 13 of 20, top-5 11 -> 14. Details notes/14.")
    (ts "2026-09-26T23:01:07Z"))
   ((agent "claude")
    (checks (((cmd "raco test tests/doc-test.rkt") (secs 16.6))))
    (kind done)
    (seq 138)
    (ts "2026-09-26T23:01:24Z")
    (verified #t)))))
