((id "T13")
 (title "A2 binding and arity checker: unbound ids with nearest exports, bad requires, arity")
 (status open)
 (priority 2)
 (goal #f)
 (after ("T11" "T12"))
 (checks ("raco test tests/binding-test.rkt"))
 (anchors (((hash "9c4dbad71fae") (ref "steer/srcread.rkt#read-racket-source"))))
 (touches ())
 (tags ("tool"))
 (claimed-by #f)
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T06:14:34Z")
 (log ()))
