((id "T14")
 (title "A3 blame-returning check loop: raco make + raco test + contracts in one report")
 (status open)
 (priority 2)
 (goal #f)
 (after ("T11"))
 (checks ("raco test tests/checkloop-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("tool"))
 (claimed-by #f)
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T06:14:34Z")
 (log ()))
