((id "T16")
 (title "F4 architecture rules: require-graph facts + #lang datalog rules, report violating edges")
 (status open)
 (priority 3)
 (goal
  "Layering/allowed-caller rules. Datalog has no negation (tested), so rules are positive; exceptions via explicit allow facts.")
 (after ())
 (checks ("raco test tests/rules-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("drift"))
 (claimed-by #f)
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T06:14:34Z")
 (log ()))
