((id "T16")
 (title "F4 architecture rules: require-graph facts + #lang datalog rules, report violating edges")
 (status done)
 (priority 3)
 (goal
  "Layering/allowed-caller rules. Datalog has no negation (tested), so rules are positive; exceptions via explicit allow facts.")
 (after ())
 (checks ("raco test tests/rules-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("drift"))
 (claimed-by "claude")
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T23:14:11Z")
 (log
  (((agent "claude")
    (kind note)
    (seq 145)
    (text
     "Built steer/rules.rkt: datalog/parse for parsing, own bottom-up evaluator (the package's prove returned no answers in this environment), %layer glob directives, reach() prelude, violation/2,3 reported with the require path and the offending line. Dogfooded: .steer/rules.dl for steer itself, checked by tests/rules-test.rkt; mutation test caught a core->command dependency. Details notes/15.")
    (ts "2026-09-26T23:14:05Z"))
   ((agent "claude")
    (checks (((cmd "raco test tests/rules-test.rkt") (secs 2.3))))
    (kind done)
    (seq 147)
    (ts "2026-09-26T23:14:11Z")
    (verified #t)))))
