((id "T17")
 (title
  "F6 purpose manifest: declared responsibilities per module; flag uncovered exports/requires")
 (status open)
 (priority 4)
 (goal #f)
 (after ("T16"))
 (checks ("raco test tests/manifest-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("drift"))
 (claimed-by #f)
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T06:14:34Z")
 (log ()))
