((id "T18")
 (title "F5b token winnowing clones: near-miss and non-Racket files; `steer dup --like file#name`")
 (status open)
 (priority 3)
 (goal #f)
 (after ())
 (checks ("raco test tests/winnow-test.rkt"))
 (anchors (((hash "e68dfc3ff69d") (ref "steer/dup.rkt#find-clones"))))
 (touches ())
 (tags ("drift" "cross-language"))
 (claimed-by #f)
 (github ((digest "283fb942a8bd") (kind issue) (number 13)))
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T08:05:03Z")
 (log ()))
