((id "T2")
 (title "F2 symbol anchors: datum hashes, heuristic finder for other languages, stale/refresh")
 (status done)
 (priority 2)
 (goal #f)
 (after ("T1"))
 (checks ("raco test tests/unit-test.rkt"))
 (anchors (((hash "b97e8c126ece") (ref "steer/anchors.rkt#resolve-anchor"))))
 (touches ())
 (tags ("built"))
 (claimed-by "claude")
 (created "2026-09-26T06:13:22Z")
 (updated "2026-09-26T06:13:34Z")
 (log
  (((agent "claude")
    (checks (((cmd "raco test tests/unit-test.rkt") (secs 0.8))))
    (kind done)
    (seq 11)
    (ts "2026-09-26T06:13:34Z")
    (verified #t)))))
