((id "T21")
 (title
  "Task ids collide across git branches (both create T7): add `steer doctor` to detect and renumber")
 (status done)
 (priority 2)
 (goal #f)
 (after ())
 (checks ("raco test tests/doctor-test.rkt"))
 (anchors (((hash "f83ae16d6f2b") (ref "steer/store.rkt#next-id"))))
 (touches ())
 (tags ("tracker"))
 (claimed-by "claude")
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T23:05:02Z")
 (log
  (((agent "claude")
    (kind note)
    (seq 95)
    (text
     "Partial mitigation added: .gitattributes merge=union for .steer/events.rktd, so appends from two branches merge cleanly. Sequence numbers can still repeat across branches, and task ids can still collide; doctor still needed.")
    (ts "2026-09-26T08:04:16Z"))
   ((agent "claude")
    (kind note)
    (seq 139)
    (text
     "Built steer doctor: integrity checks; --against REF finds ids the other branch uses for a different task (same id, different title or created); --fix renumbers OURS above the highest id on either side, repoints after-references, resequences union-merged events. Tested with a real two-branch git scenario. Not covered: GitHub issue titles keep the old id until the next github sync (the task digest changes, so sync updates them).")
    (ts "2026-09-26T23:04:57Z"))
   ((agent "claude")
    (checks (((cmd "raco test tests/doctor-test.rkt") (secs 2.4))))
    (kind done)
    (seq 141)
    (ts "2026-09-26T23:05:02Z")
    (verified #t)))))
