((id "T22")
 (title "Measure `steer syntax` fix-location accuracy on a corpus of seeded paren errors")
 (status done)
 (priority 3)
 (goal #f)
 (after ("T8"))
 (checks ("test -f notes/10-syntax-accuracy.md"))
 (anchors (((hash "04b8c7298905") (ref "steer/syntax-check.rkt#scan-findings"))))
 (touches ())
 (tags ("measure"))
 (claimed-by "claude")
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T07:58:37Z")
 (log
  (((agent "claude")
    (kind note)
    (seq 64)
    (text
     "Measured: 0 false positives on 6,291 corpus files after header fixes; exact repair 58% -> 86% after indentation-guided verified repair (fresh seed agrees). Added steer syntax --fix (verified edits only). Details in notes/10.")
    (ts "2026-09-26T07:58:37Z"))
   ((agent "claude")
    (checks (((cmd "test -f notes/10-syntax-accuracy.md") (secs 0.0))))
    (kind done)
    (seq 65)
    (ts "2026-09-26T07:58:37Z")
    (verified #t)))))
