((id "T23")
 (title "A1b structural edit tool: apply edits by form path so models never retype whole forms")
 (status open)
 (priority 3)
 (goal #f)
 (after ("T9"))
 (checks ("raco test tests/apply-edit-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("tool"))
 (claimed-by #f)
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T06:14:34Z")
 (log ()))
