((id "T26")
 (title "Choose a LICENSE for the public repo (none yet = all rights reserved)")
 (status open)
 (priority 1)
 (goal #f)
 (after ())
 (checks ("test -f LICENSE"))
 (anchors ())
 (touches ())
 (tags ("human"))
 (claimed-by #f)
 (created "2026-09-26T07:17:19Z")
 (updated "2026-09-26T07:17:19Z")
 (log ()))
