((id "T28")
 (title "Define the criteria grammar and parser (EARS shapes) with located errors")
 (status open)
 (priority 1)
 (goal
  "steer/spec.rkt: parser-tools lexer + LALR grammar for the five EARS shapes (ubiquitous, WHEN event, WHILE state, IF-THEN unwanted, WHERE optional) plus a <response> that names an observable (writes/returns/refuses/exits with/prints/contains). parse-criteria returns a structured form; every parse error carries line:col, the token seen and the template expected (note 03 rule).")
 (after ())
 (checks ("raco test tests/spec-test.rkt"))
 (anchors (((hash #f) (ref "steer/spec.rkt#parse-criteria"))))
 (touches ())
 (tags ("regular-grammar"))
 (claimed-by #f)
 (created "2026-09-26T07:48:36Z")
 (updated "2026-09-26T07:48:37Z")
 (log ()))
