((id "T28")
 (title "Define the criteria grammar and parser (EARS shapes) with located errors")
 (status done)
 (priority 1)
 (goal
  "steer/spec.rkt: parser-tools lexer + LALR grammar for the five EARS shapes (ubiquitous, WHEN event, WHILE state, IF-THEN unwanted, WHERE optional) plus a <response> that names an observable (writes/returns/refuses/exits with/prints/contains). parse-criteria returns a structured form; every parse error carries line:col, the token seen and the template expected (note 03 rule).")
 (after ())
 (checks ("raco test tests/spec-test.rkt"))
 (anchors (((hash #f) (ref "steer/spec.rkt#parse-criteria"))))
 (touches ())
 (tags ("regular-grammar"))
 (claimed-by "g2-m1")
 (github ((digest "75e0f4a7b0de") (kind issue) (number 1)))
 (created "2026-09-26T07:48:36Z")
 (updated "2026-09-27T04:04:35Z")
 (log
  (((agent "g2-m1")
    (kind note)
    (seq 149)
    (text
     "Design: parser-tools lexer (words, comma; keywords when/while/if/then/where/shall/the case-insensitive) + LALR grammar over token classes WORD/VERB/THE. The observable-verb requirement is in the grammar (lexer classifies observable verbs as VERB, weak modals as WEAK), so 'the code SHALL work' is a parse error with the verb list. Final period handled before parsing (better message). Error explanation derived from token context because yacc gives no expected-set.")
    (ts "2026-09-27T04:02:46Z"))
   ((agent "g2-m1")
    (checks (((cmd "raco test tests/spec-test.rkt") (secs 2.4))))
    (kind done)
    (seq 150)
    (ts "2026-09-27T04:04:35Z")
    (verified #t)))))
