((id "T29")
 (title "Lint rules that reject vague criteria with a fix")
 (status open)
 (priority 1)
 (goal
  "lint-criteria flags weak modals (should, may, could), open-ended words (etc., appropriate, as needed, and/or, fast, user-friendly), passives without an agent and quantities without a unit; each finding has kind, location and a rewrite suggestion in the controlled form. Rule list is data so it can grow from measured failures (note 04 taxonomy).")
 (after ("T28"))
 (checks ("raco test tests/spec-lint-test.rkt"))
 (anchors (((hash #f) (ref "steer/spec.rkt#lint-criteria"))))
 (touches ())
 (tags ("regular-grammar"))
 (claimed-by #f)
 (github ((digest "fa88f76ab715") (kind issue) (number 2)))
 (created "2026-09-26T07:48:36Z")
 (updated "2026-09-26T08:03:39Z")
 (log ()))
