((id "T29")
 (title "Lint rules that reject vague criteria with a fix")
 (status done)
 (priority 1)
 (goal
  "lint-criteria flags weak modals (should, may, could), open-ended words (etc., appropriate, as needed, and/or, fast, user-friendly), passives without an agent and quantities without a unit; each finding has kind, location and a rewrite suggestion in the controlled form. Rule list is data so it can grow from measured failures (note 04 taxonomy).")
 (after ("T28"))
 (checks ("raco test tests/spec-lint-test.rkt"))
 (anchors (((hash #f) (ref "steer/spec.rkt#lint-criteria"))))
 (touches ())
 (tags ("regular-grammar"))
 (claimed-by "g2-m1")
 (github ((digest "fa88f76ab715") (kind issue) (number 2)))
 (created "2026-09-26T07:48:36Z")
 (updated "2026-09-27T04:07:17Z")
 (log
  (((agent "g2-m1")
    (kind note)
    (seq 152)
    (text
     "Lint rules are data: (id severity matcher scope message fix). Matcher is a regexp or a procedure (bare-quantity needs the word after the number). Passive is scoped to the response, since a condition like 'the file is locked' describes a state. Errors: open-ended, and/or, subjective, hedge, vague quantity; warnings: bare quantity, agent-less passive. --lax (cmd) will demote errors to warnings.")
    (ts "2026-09-27T04:05:33Z"))
   ((agent "g2-m1")
    (kind note)
    (seq 153)
    (text
     "Found by the tests: clause keywords (if/where/then/when/while) must be plain words inside a phrase ('keep the file if necessary'); and 'at most' must not trip the vague-quantity rule for 'most'. Both fixed with regression tests. Verb list widened after note 11's own example ('SHALL export') was rejected; false-reject rate is measured in M3 (T38).")
    (ts "2026-09-27T04:07:13Z"))
   ((agent "g2-m1")
    (checks (((cmd "raco test tests/spec-lint-test.rkt") (secs 2.5))))
    (kind done)
    (seq 154)
    (ts "2026-09-27T04:07:17Z")
    (verified #t)))))
