((id "T30")
 (title "Deterministic renderer: structured criterion to canonical prose and JSON")
 (status open)
 (priority 1)
 (goal
  "render-criteria prints the canonical EARS sentence (and the note-03 JSON with --json) from the structured form, so humans read prose the model never had to write. Property: parse(render(x)) = x on every fixture.")
 (after ("T28"))
 (checks ("raco test tests/spec-render-test.rkt"))
 (anchors (((hash #f) (ref "steer/spec.rkt#render-criteria"))))
 (touches ())
 (tags ("regular-grammar"))
 (claimed-by #f)
 (created "2026-09-26T07:48:36Z")
 (updated "2026-09-26T07:48:38Z")
 (log ()))
