((id "T30")
 (title "Deterministic renderer: structured criterion to canonical prose and JSON")
 (status done)
 (priority 1)
 (goal
  "render-criteria prints the canonical EARS sentence (and the note-03 JSON with --json) from the structured form, so humans read prose the model never had to write. Property: parse(render(x)) = x on every fixture.")
 (after ("T28"))
 (checks ("raco test tests/spec-render-test.rkt"))
 (anchors (((hash #f) (ref "steer/spec.rkt#render-criteria"))))
 (touches ())
 (tags ("regular-grammar"))
 (claimed-by "g2-m1")
 (github ((digest "271c885713db") (kind issue) (number 3)))
 (created "2026-09-26T07:48:36Z")
 (updated "2026-09-27T04:08:48Z")
 (log
  (((agent "g2-m1")
    (kind note)
    (seq 156)
    (text
     "Renderer: canonical sentence (keywords upper, verb lower, single spaces); the object may start with a comma so render joins without a space. parse(render(x))=x verified on fixtures and 400 random criteria (with keywords inside phrases, empty and comma-led responses); render is idempotent. JSON uses null for an absent condition.")
    (ts "2026-09-27T04:08:45Z"))
   ((agent "g2-m1")
    (checks (((cmd "raco test tests/spec-render-test.rkt") (secs 2.5))))
    (kind done)
    (seq 157)
    (ts "2026-09-27T04:08:48Z")
    (verified #t)))))
