((id "T31")
 (title "Wire `steer spec check|render FILE|-` into the CLI")
 (status done)
 (priority 1)
 (goal
  "steer/cmd-spec.rkt registered in main.rkt's command table with help text, exit codes (0 ok, 1 findings, 2 usage) and the finding cap. Reads a file or stdin, one criterion per line, comments allowed.")
 (after ("T28" "T29" "T30"))
 (checks ("raco test tests/spec-cmd-test.rkt"))
 (anchors
  (((hash "49e56235effb") (ref "steer/main.rkt#commands"))
   ((hash "2a78f4b2991a") (ref "steer/cmd-spec.rkt#cmd-spec"))))
 (touches ())
 (tags ("regular-grammar"))
 (claimed-by "g2-m1")
 (github ((digest "ee24e33f94da") (kind issue) (number 4)))
 (created "2026-09-26T07:48:36Z")
 (updated "2026-09-27T04:11:36Z")
 (log
  (((agent "g2-m1")
    (kind note)
    (seq 159)
    (text
     "cmd-spec.rkt: check prints the parsed structure for valid lines (L<n> shape: system -> verb object (when: ...)) plus located findings; render prints canonical sentences for lines that parse and reports the rest; --lax demotes lint errors only (the grammar is never relaxed); no criteria at all is a refusal, not a pass. Added failure class criteria-error so M3 can count criteria mistakes. Added steer/spec.rkt to the core layer of .steer/rules.dl.")
    (ts "2026-09-27T04:11:13Z"))
   ((agent "g2-m1")
    (checks (((cmd "raco test tests/spec-cmd-test.rkt") (secs 21.0))))
    (kind done)
    (seq 161)
    (ts "2026-09-27T04:11:36Z")
    (verified #t)))))
