((id "T34")
 (title "Coverage: which check covers which criterion, and what is uncovered")
 (status open)
 (priority 2)
 (goal
  "A criterion is covered when a #:check names it (`--check 'raco test t.rkt' --covers 2`) or is marked manual with a reason. uncovered-criteria is plain Racket (datalog has no negation, note 06); facts are also exported as Datalog for cross-task queries (which tasks cover requirement R). `steer show` lists criteria with their covering check or `uncovered`.")
 (after ("T33"))
 (checks ("raco test tests/spec-coverage-test.rkt"))
 (anchors (((hash #f) (ref "steer/spec.rkt#uncovered-criteria"))))
 (touches ())
 (tags ("regular-grammar"))
 (claimed-by #f)
 (created "2026-09-26T07:48:37Z")
 (updated "2026-09-26T07:48:38Z")
 (log ()))
