((id "T37")
 (title "M2 · criteria live on tasks and gate `done`")
 (status open)
 (priority 2)
 (goal
  "Milestone: import a plan with criteria, see them in show/resume, watch done refuse the uncovered one, add a covering check, done passes. Proven end to end through the CLI.")
 (after ("T32" "T33" "T34" "T35" "T36"))
 (checks ("raco test tests/spec-tracker-cli-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("regular-grammar" "milestone"))
 (claimed-by #f)
 (github ((digest "5cc16827e13d") (kind milestone) (number 2)))
 (created "2026-09-26T07:48:37Z")
 (updated "2026-09-26T08:03:24Z")
 (log ()))
