((id "T39")
 (title "Measure false rejects and the rewrite cost in tokens")
 (status open)
 (priority 2)
 (goal
  "Run steer spec check over the corpus: acceptance rate, false rejects (valid requirements refused), lint false positives, and the token cost of the controlled form versus the original (tiktoken/HF proxies; count_tokens when an API key is present, labelled). Results with method in notes/13-criteria-results.md.")
 (after ("T38"))
 (checks ("grep -q 'false-reject' notes/13-criteria-results.md"))
 (anchors ())
 (touches ())
 (tags ("regular-grammar"))
 (claimed-by #f)
 (created "2026-09-26T07:48:37Z")
 (updated "2026-09-26T07:48:39Z")
 (log ()))
