((id "T4")
 (title "F3 API lock for Racket modules: exports, arity, keywords, contracts; breaking-change diff")
 (status done)
 (priority 2)
 (goal #f)
 (after ())
 (checks ("raco test tests/unit-test.rkt"))
 (anchors (((hash "b1c07ffcfca5") (ref "steer/api.rkt#api-diff"))))
 (touches ())
 (tags ("built"))
 (claimed-by "claude")
 (created "2026-09-26T06:13:22Z")
 (updated "2026-09-26T06:13:45Z")
 (log
  (((agent "claude")
    (checks (((cmd "raco test tests/unit-test.rkt") (secs 0.9))))
    (kind done)
    (seq 15)
    (ts "2026-09-26T06:13:45Z")
    (verified #t)))))
