((id "T40")
 (title "Agentic runs: prose goal vs criteria vs criteria plus gate")
 (status open)
 (priority 2)
 (goal
  "Note 04 T5 conditions on ~20 tasks with hidden tests: (a) prose goal, (b) criteria + derived checks, (c) b + done gate. Metrics: wrong done claims, pass rate, tokens and turns per solved task; interleaved runs, fixed seeds, model ids recorded, hold-out untouched. Needs the E1 attempt logger (T7) to record attempts.")
 (after ("T37" "T39" "T7"))
 (checks ("grep -q 'cost per solved task' notes/13-criteria-results.md"))
 (anchors ())
 (touches ())
 (tags ("regular-grammar"))
 (claimed-by #f)
 (github ((digest "7116f6d68f58") (kind issue) (number 11)))
 (created "2026-09-26T07:48:37Z")
 (updated "2026-09-26T08:03:45Z")
 (log ()))
