((id "T42")
 (title "M3 · the criteria tool is measured and decided")
 (status open)
 (priority 2)
 (goal
  "Milestone: corpus, false-reject rate, agentic comparison and a decision all exist and agree; scripts/criteria-eval.rkt status --require exits non-zero until every artefact is present.")
 (after ("T37" "T38" "T39" "T40" "T41"))
 (checks ("racket scripts/criteria-eval.rkt status --require"))
 (anchors ())
 (touches ())
 (tags ("regular-grammar" "milestone"))
 (claimed-by #f)
 (github ((digest "2e12cac21f11") (kind milestone) (number 3)))
 (created "2026-09-26T07:48:37Z")
 (updated "2026-09-26T08:03:24Z")
 (log ()))
