((id "T44")
 (title "Route `steer syntax` and the post-edit hook by file extension")
 (status done)
 (priority 1)
 (goal
  "A .py or .cs edit gets its language's gate (or an explicit `skipped` finding) instead of the Racket reader's false errors or silence; one registry (steer/lang.rkt) maps extension to gate so later tasks only add entries.")
 (after ())
 (checks ("raco test tests/lang-route-test.rkt"))
 (anchors
  (((hash "ab09d982fd8e") (ref "steer/cmd-code.rkt#post-edit-problems"))
   ((hash "ee9d61c4540b") (ref "steer/cmd-code.rkt#cmd-syntax"))))
 (touches ())
 (tags ("cross-language"))
 (claimed-by "xl1")
 (github ((digest "6c736d1972e7") (kind issue) (number 14)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-27T04:28:19Z")
 (log
  (((agent "xl1")
    (kind note)
    (seq 149)
    (text
     "steer/lang.rkt: a gate registry (name exts unit check); lang-check returns (fs n lang unit); unknown extension -> one info 'skipped' finding, counted as neither clean nor broken. Both cmd-syntax and post-edit-problems route through it. The hook stays silent on unsupported files on purpose (a note per .md edit would be ignored); steer syntax reports 'skipped'. Before: a valid .py got a false read-error from the Racket reader; now skipped until T45 adds the python gate.")
    (ts "2026-09-27T04:27:54Z"))
   ((agent "xl1")
    (checks (((cmd "raco test tests/lang-route-test.rkt") (secs 21.0))))
    (kind done)
    (seq 151)
    (ts "2026-09-27T04:28:19Z")
    (verified #t)))))
