((id "T45")
 (title "Python syntax gate from the stdlib ast, normalised to findings")
 (status done)
 (priority 1)
 (goal
  "An embedded worker script (the api.rkt pattern) runs `ast.parse` and returns SyntaxError msg/line/col/end as a located finding, with a machine-applicable edit for the shapes Python names precisely ('(' was never closed, expected ':'). Falls back to `skipped` when python3 is missing; under 100 ms.")
 (after ("T44"))
 (checks ("raco test tests/py-syntax-test.rkt"))
 (anchors
  (((hash "9fecd43c105b") (ref "steer/syntax-check.rkt#check-source"))
   ((hash "e346686238aa") (ref "steer/api.rkt#api-describe"))))
 (touches ())
 (tags ("cross-language"))
 (claimed-by "xl1")
 (github ((digest "dddbe3af7e8b") (kind issue) (number 16)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-27T04:36:57Z")
 (log
  (((agent "xl1")
    (kind note)
    (seq 153)
    (text
     "python.rkt: worker script embedded, run as python3 -I -S -c (isolated, no site). compile(ast) not just parse, so semantic errors (return outside function) are found. Edits are candidate-and-verify: a small family of edits near the error (closer before a header's colon, at a statement's end, before a mismatched closer, delete an unmatched one, add a colon), earliest first, 2 s budget, offered only if the file compiles afterwards. First version tried only the statement end: 9/41 deletions got an edit; after adding header/colon and mismatch candidates: 36/41 get one and 34/41 restore the original exactly (misses: 3 braces inside an f-string, a closer at the start of a signature line). Timing could not be verified: load average was 334; bare python startup was 62-102 ms, gate adds ~40 ms.")
    (ts "2026-09-27T04:36:24Z"))
   ((agent "xl1")
    (checks (((cmd "raco test tests/py-syntax-test.rkt") (secs 31.4))))
    (kind done)
    (seq 154)
    (ts "2026-09-27T04:36:57Z")
    (verified #t)))))
