((id "T46")
 (title "C# structural gate: brace and string aware scanner for the hook")
 (status done)
 (priority 2)
 (goal
  "Generalise the bracket scanner to C-family lexing (// and /* */ comments, \"..\" with escapes, @verbatim, $interpolated with nested braces, raw \"\"\" strings, 'c' literals, #directives) so unclosed/mismatched braces are located with a fix in under 50 ms, without dotnet.")
 (after ("T44"))
 (checks ("raco test tests/cs-syntax-test.rkt"))
 (anchors (((hash "4742931e15b3") (ref "steer/syntax-check.rkt#scan-findings"))))
 (touches ())
 (tags ("cross-language"))
 (claimed-by "xl1")
 (github ((digest "edf5b50210cc") (kind issue) (number 17)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-27T04:43:45Z")
 (log
  (((agent "xl1")
    (kind note)
    (seq 156)
    (text
     "csharp.rkt: a C# lexer that knows regular, verbatim, interpolated (nested strings, {{ }}, format specs), raw and $$ raw strings, char literals, comments, # directives, @identifiers; no dotnet needed. Bracket check with candidate-and-verify edits, ranked by indentation violations. First version blamed the outer namespace brace and put the closer at EOF when a closer was missing inside (the unmatched brace at EOF belongs to an outer block): now candidates also come from every indentation-violation site and the finding is located at the edit. Fixture deletions of every } in Shapes.cs: 21/21 detected, 21/21 verified, 14/21 restore the original (modulo the whitespace-only line a deleted brace leaves). Gate time: 2 ms on 2000 lines, 1 ms on the fixture.")
    (ts "2026-09-27T04:43:34Z"))
   ((agent "xl1")
    (checks (((cmd "raco test tests/cs-syntax-test.rkt") (secs 10.1))))
    (kind done)
    (seq 157)
    (ts "2026-09-27T04:43:45Z")
    (verified #t)))))
