((id "T46")
 (title "C# structural gate: brace and string aware scanner for the hook")
 (status open)
 (priority 2)
 (goal
  "Generalise the bracket scanner to C-family lexing (// and /* */ comments, \"..\" with escapes, @verbatim, $interpolated with nested braces, raw \"\"\" strings, 'c' literals, #directives) so unclosed/mismatched braces are located with a fix in under 50 ms, without dotnet.")
 (after ("T44"))
 (checks ("raco test tests/cs-syntax-test.rkt"))
 (anchors (((hash "4742931e15b3") (ref "steer/syntax-check.rkt#scan-findings"))))
 (touches ())
 (tags ("cross-language"))
 (claimed-by #f)
 (github ((digest "edf5b50210cc") (kind issue) (number 17)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-26T08:05:16Z")
 (log ()))
