((id "T47")
 (title "Parse pytest, dotnet test and rackunit output so `done` shows the first failing test")
 (status done)
 (priority 1)
 (goal
  "Recognise the runner from the command or output and emit at most 3 findings per failed check with test id, file:line and the first message line (raw tail behind --full); today dotnet test loses the first failures and clips file:line, and pytest is readable only with -q.")
 (after ())
 (checks ("raco test tests/test-output-test.rkt"))
 (anchors
  (((hash "4dd97631a196") (ref "steer/checks.rkt#run-check"))
   ((hash "3f03f3a9b7b7") (ref "steer/checks.rkt#tail-text"))
   ((hash "5908e2b7b2c3") (ref "steer/cmd-tasks.rkt#check-findings"))))
 (touches ())
 (tags ("cross-language"))
 (claimed-by "xl1")
 (github ((digest "4c4fc99db9b8") (kind issue) (number 15)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-27T04:51:26Z")
 (log
  (((agent "xl1")
    (kind note)
    (seq 159)
    (text
     "steer/testparse.rkt: parse-test-output(cmd, output) detects pytest/dotnet/rackunit from the command or the output's own signature, returns failures (id file line message) in report order + a one-line summary. checks.rkt now keeps up to 1MiB of output (was a 64KiB tail only), so a long dotnet run's first failures are not lost. check-findings in cmd-tasks.rkt shows the summary in the headline plus up to 3 test-failed findings, --full/--limit lift the cap, unrecognised output falls back to the old raw tail unchanged. Fixtures are sanitized REAL runs (pytest 9.1, dotnet 10 xunit on a broken GuardClauses copy, raco test), not synthesized: tests/fixtures/test-output/. Verified end to end through steer done.")
    (ts "2026-09-27T04:51:22Z"))
   ((agent "xl1")
    (checks (((cmd "raco test tests/test-output-test.rkt") (secs 4.0))))
    (kind done)
    (seq 160)
    (ts "2026-09-27T04:51:26Z")
    (verified #t)))))
