((id "T47")
 (title "Parse pytest, dotnet test and rackunit output so `done` shows the first failing test")
 (status open)
 (priority 1)
 (goal
  "Recognise the runner from the command or output and emit at most 3 findings per failed check with test id, file:line and the first message line (raw tail behind --full); today dotnet test loses the first failures and clips file:line, and pytest is readable only with -q.")
 (after ())
 (checks ("raco test tests/test-output-test.rkt"))
 (anchors
  (((hash "4dd97631a196") (ref "steer/checks.rkt#run-check"))
   ((hash "3f03f3a9b7b7") (ref "steer/checks.rkt#tail-text"))
   ((hash "5908e2b7b2c3") (ref "steer/cmd-tasks.rkt#check-findings"))))
 (touches ())
 (tags ("cross-language"))
 (claimed-by #f)
 (github ((digest "4c4fc99db9b8") (kind issue) (number 15)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-26T08:05:04Z")
 (log ()))
