((id "T48")
 (title "Parse MSBuild and Python traceback diagnostics from failed checks")
 (status open)
 (priority 2)
 (goal
  "When a check fails at build or import time, `file(line,col): error CSnnnn: msg` and Python `File \"f\", line N` / SyntaxError blocks become located findings through the same parser registry, so compile errors in `done` read like test failures.")
 (after ("T47"))
 (checks ("raco test tests/diag-output-test.rkt"))
 (anchors (((hash "3f03f3a9b7b7") (ref "steer/checks.rkt#tail-text"))))
 (touches ())
 (tags ("cross-language"))
 (claimed-by #f)
 (github ((digest "f4020193cb53") (kind issue) (number 18)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-26T08:05:17Z")
 (log ()))
