((id "T48")
 (title "Parse MSBuild and Python traceback diagnostics from failed checks")
 (status done)
 (priority 2)
 (goal
  "When a check fails at build or import time, `file(line,col): error CSnnnn: msg` and Python `File \"f\", line N` / SyntaxError blocks become located findings through the same parser registry, so compile errors in `done` read like test failures.")
 (after ("T47"))
 (checks ("raco test tests/diag-output-test.rkt"))
 (anchors (((hash "3f03f3a9b7b7") (ref "steer/checks.rkt#tail-text"))))
 (touches ())
 (tags ("cross-language"))
 (claimed-by "xl1")
 (github ((digest "f4020193cb53") (kind issue) (number 18)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-27T04:56:21Z")
 (log
  (((agent "xl1")
    (kind note)
    (seq 162)
    (text
     "parse-diagnostics(output) in testparse.rkt: MSBuild (path(line,col): error CSnnnn: msg [proj], deduped since MSBuild prints each diagnostic twice) and Python tracebacks (last frame = where it happened, not the caller; exception chaining -> multiple failures). Only consulted in check-findings when parse-test-output found nothing, so a build failure never masquerades as a test failure; new finding kinds diag-failed/diag-failed-more and E1 class build-failed keep the distinction through to the taxonomy. Fixtures: two real dotnet builds of a broken GuardClauses copy (one syntax CS1026, one CS0103+2 warnings) and two real python3 tracebacks (ZeroDivisionError, ModuleNotFoundError).")
    (ts "2026-09-27T04:56:19Z"))
   ((agent "xl1")
    (checks (((cmd "raco test tests/diag-output-test.rkt") (secs 1.6))))
    (kind done)
    (seq 163)
    (ts "2026-09-27T04:56:21Z")
    (verified #t)))))
