((id "T5")
 (title "F5 Racket clone detection (alpha-renamed subtree hashing, maximal groups)")
 (status done)
 (priority 2)
 (goal #f)
 (after ())
 (checks ("raco test tests/unit-test.rkt"))
 (anchors (((hash "e68dfc3ff69d") (ref "steer/dup.rkt#find-clones"))))
 (touches ())
 (tags ("built"))
 (claimed-by "claude")
 (created "2026-09-26T06:13:22Z")
 (updated "2026-09-26T06:13:47Z")
 (log
  (((agent "claude")
    (checks (((cmd "raco test tests/unit-test.rkt") (secs 1.0))))
    (kind done)
    (seq 17)
    (ts "2026-09-26T06:13:47Z")
    (verified #t)))))
