((id "T51")
 (title "Warn with did-you-mean when an anchor's file exists but its name does not")
 (status done)
 (priority 2)
 (goal
  "`add`/`import`/`edit` distinguish `not yet created` (file absent or name declared new) from `unresolved` (file present, no such definition) and suggest the closest definition names in that file, so typos, qualified names and generics stop hiding as pending anchors.")
 (after ("T49" "T50"))
 (checks ("raco test tests/anchor-suggest-test.rkt"))
 (anchors
  (((hash "e7bcdd631eb5") (ref "steer/cmd-tasks.rkt#cmd-add"))
   ((hash "67f9dc8300ab") (ref "steer/cmd-tasks.rkt#cmd-import"))))
 (touches ())
 (tags ("cross-language"))
 (claimed-by "xl1")
 (github ((digest "12a59630cc00") (kind issue) (number 21)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-27T05:25:20Z")
 (log
  (((agent "xl1")
    (kind note)
    (seq 171)
    (text
     "Added anchor-names-in-file (racket/python.rkt/csharp.rkt) and miss-with-suggestion in anchors.rkt: resolve-anchor's not-found result now carries file-exists? and suggestions (an ambiguity list when the worker already has one, else fuzzy closest-match against every name in the file). cmd-add/cmd-import/cmd-edit --add-anchor call anchor-not-found-findings to turn this into anchor-pending (file absent: info) vs anchor-unresolved (file exists, name wrong: warning + did-you-mean), instead of both reading as the same silent 'pending'. Stored anchor records are unchanged (still just ref+hash); the diagnosis is recomputed at add/import/edit time only, not persisted.")
    (ts "2026-09-27T05:25:13Z"))
   ((agent "xl1")
    (checks (((cmd "raco test tests/anchor-suggest-test.rkt") (secs 6.7))))
    (kind done)
    (seq 172)
    (ts "2026-09-27T05:25:20Z")
    (verified #t)))))
