((id "T52")
 (title "Make the steer-code skill, help and hook docs language-aware")
 (status open)
 (priority 2)
 (goal
  "The skill and `steer help syntax|stale|done` state per language what runs, what is exact and what is skipped, so an agent on a Python or C# project neither over-trusts nor ignores the tools; README known-limits updated.")
 (after ("T45" "T46" "T47" "T49" "T50"))
 (checks ("raco test tests/skill-docs-test.rkt"))
 (anchors (((hash "de1ed9fb351c") (ref "steer/main.rkt#hook-config"))))
 (touches ())
 (tags ("cross-language"))
 (claimed-by #f)
 (github ((digest "b5969e76d566") (kind issue) (number 22)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-26T08:05:20Z")
 (log ()))
