((id "T52")
 (title "Make the steer-code skill, help and hook docs language-aware")
 (status done)
 (priority 2)
 (goal
  "The skill and `steer help syntax|stale|done` state per language what runs, what is exact and what is skipped, so an agent on a Python or C# project neither over-trusts nor ignores the tools; README known-limits updated.")
 (after ("T45" "T46" "T47" "T49" "T50"))
 (checks ("raco test tests/skill-docs-test.rkt"))
 (anchors (((hash "de1ed9fb351c") (ref "steer/main.rkt#hook-config"))))
 (touches ())
 (tags ("cross-language"))
 (claimed-by "xl1")
 (github ((digest "b5969e76d566") (kind issue) (number 22)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-27T05:34:31Z")
 (log
  (((agent "xl1")
    (kind note)
    (seq 174)
    (text
     "One shared language-coverage-table in main.rkt feeds steer help syntax|stale|done (so the three texts cannot drift apart) plus a rewritten steer-code skill and README known-limits/tool-table. Two real bugs found only by testing the rendered text: Racket #<<EOF heredocs do NOT include a trailing newline (needed \\n\\n, not \\n, to get a blank line before the following paragraph), and pregexp does not support \\n or \\z as escapes (need an actual newline character, built via string-append outside the #px reader, and $ instead of \\z). Installed .claude/skills/ was stale until steer/compiled/skills_rkt.zo was deleted and steer rebuilt: skills.rkt's embedded-skills macro only re-embeds skills/ content when raco make actually recompiles that module.")
    (ts "2026-09-27T05:34:28Z"))
   ((agent "xl1")
    (checks (((cmd "raco test tests/skill-docs-test.rkt") (secs 1.0))))
    (kind done)
    (seq 175)
    (ts "2026-09-27T05:34:31Z")
    (verified #t)))))
