((id "T53")
 (title "XL1 · Cross-language steering v1: Python and C# gates, anchors, readable check failures")
 (status open)
 (priority 1)
 (goal
  "End to end on a Python fixture and a C# fixture (C# cases skip without dotnet, as in CI): init, import with Class.method anchors, body edit → stale, broken syntax → hook exit 2 with a located finding, failing test → done shows the failing test with file:line.")
 (after ("T44" "T45" "T46" "T47" "T48" "T49" "T50" "T51" "T52"))
 (checks ("raco test tests/xlang-integration-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("cross-language" "milestone"))
 (claimed-by #f)
 (github ((digest "5581d7cf0b8d") (kind milestone) (number 4)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-26T08:05:01Z")
 (log ()))
