((id "T53")
 (title "XL1 · Cross-language steering v1: Python and C# gates, anchors, readable check failures")
 (status done)
 (priority 1)
 (goal
  "End to end on a Python fixture and a C# fixture (C# cases skip without dotnet, as in CI): init, import with Class.method anchors, body edit → stale, broken syntax → hook exit 2 with a located finding, failing test → done shows the failing test with file:line.")
 (after ("T44" "T45" "T46" "T47" "T48" "T49" "T50" "T51" "T52"))
 (checks ("raco test tests/xlang-integration-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("cross-language" "milestone"))
 (claimed-by "xl1")
 (github ((digest "5581d7cf0b8d") (kind milestone) (number 4)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-27T05:39:41Z")
 (log
  (((agent "xl1")
    (kind note)
    (seq 177)
    (text
     "Milestone gate tests/xlang-integration-test.rkt: a full agent session on a Python file and a C# file through the real CLI (no dotnet SDK needed anywhere: the one dotnet-test-shaped check output is simulated from a real sanitized fixture, proving the parser, not the SDK). Covers: init, import with an exact Class.method anchor, a body edit making it stale, a comment-only edit NOT making it stale, broken syntax -> hook exit 2 with a located verified repair, --fix, a real logic bug caught by done with file:line (pytest half skips loudly if pytest is not importable), and the anchor-pending vs anchor-unresolved distinction for both languages. 858 tests pass across tests/; make test-bin passes (58). syntax-check.rkt's only diff on this branch is an export addition (edit-text), no Racket-path logic change, so scripts/syntax-accuracy.rkt was not rerun (samples/ is not fetched in this worktree and the diff cannot have moved the numbers).")
    (ts "2026-09-27T05:39:37Z"))
   ((agent "xl1")
    (checks (((cmd "raco test tests/xlang-integration-test.rkt") (secs 4.0))))
    (kind done)
    (seq 178)
    (ts "2026-09-27T05:39:41Z")
    (verified #t)))))
