((id "T55")
 (title "Single-file Roslyn worker for exact C# declarations and diagnostics")
 (status open)
 (priority 3)
 (goal
  "Ship the .NET 10 file-based app (`dotnet run worker.cs`, #:package Microsoft.CodeAnalysis.CSharp) that lists members with kinds, generic arity, parameter types, spans and normalised hashes plus syntax diagnostics; used by `steer syntax --deep` and `stale --exact` when a .NET 10 SDK is present, skipped otherwise.")
 (after ("T50"))
 (checks ("raco test tests/cs-roslyn-test.rkt"))
 (anchors (((hash "e346686238aa") (ref "steer/api.rkt#api-describe"))))
 (touches ())
 (tags ("cross-language"))
 (claimed-by #f)
 (github ((digest "f47f514360fc") (kind issue) (number 24)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-26T08:05:22Z")
 (log ()))
