((id "T57")
 (title "XL2 · Cross-language API locks and clones")
 (status open)
 (priority 3)
 (goal
  "Python and C# projects get the same drift gates Racket has: an API lock that `done` can check and clone detection over non-Racket files; verified end to end on the fixtures from M1.")
 (after ("T54" "T55" "T56" "T18"))
 (checks ("raco test tests/xlang-api-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("cross-language" "milestone"))
 (claimed-by #f)
 (github ((digest "b42824ce7039") (kind milestone) (number 5)))
 (created "2026-09-26T08:04:49Z")
 (updated "2026-09-26T08:05:02Z")
 (log ()))
