((id "T59")
 (title "Graph IR and linker over hand-written facts")
 (status open)
 (priority 1)
 (goal
  "steer/graph.rkt: def/ref/import/file-facts and gnode/gedge/graph prefab structs; a linker resolving refs by scope, imports, self/this/base receivers and name-match fallback, tagging confidence (exact/declared/name-match) and call-site arity; reachability rules (forward edges, symbol=>module=>imports=><toplevel>, class=>constructors, overrides backwards); externals and per-language stats; .rktd round-trip. This one generic module is the whole point: no per-language graph-building code anywhere else.")
 (after ("T58"))
 (checks ("raco test tests/graph-ir-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("graph"))
 (claimed-by #f)
 (created "2026-09-27T08:50:21Z")
 (updated "2026-09-27T08:50:21Z")
 (log ()))
