((id "T62")
 (title "Python extractor: implements the generic extract/resolve-import contract")
 (status open)
 (priority 1)
 (goal
  "Worker command `extract` reads a path list on stdin and prints one JSON file-facts line per file per the graph-ir contract: defs with shapes (ast.unparse), Call/Attribute/Name refs with receiver hints and positional arity, bases, decorators, Import/ImportFrom, __all__, the __main__ guard, `# steer: entry`; resolve-import maps dotted names to files under src/, top-level packages or %pyroot. This is the same contract rkt-extract and cs-extract implement - no Python-specific graph logic outside this task.")
 (after ("T59"))
 (checks ("raco test tests/py-graph-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("graph"))
 (claimed-by #f)
 (created "2026-09-27T08:50:21Z")
 (updated "2026-09-27T08:50:21Z")
 (log ()))
