((id "T63")
 (title "C# extractor: implements the generic extract/resolve-import contract, no dotnet needed")
 (status done)
 (priority 2)
 (goal
  "A body walker over each cs-member's token range emits calls (M(, this.M(, base.M(, Type.M(, new T(, method-group refs) with arity, the type's base/interface list, attributes, `using`, declared namespaces, has-statements?, and field/parameter declared types for `declared` edges, per the graph-ir contract; resolve-import maps `using X` to files declaring X. This is the same six-function contract py-extract and rkt-extract implement - the generic engine is what makes this an exact, no-SDK C# graph, not a bespoke Roslyn integration (compare T55, which stays optional).")
 (after ("T59"))
 (checks ("raco test tests/cs-graph-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("graph"))
 (claimed-by "xl3")
 (created "2026-09-27T08:50:21Z")
 (updated "2026-09-27T10:17:12Z")
 (log
  (((agent "xl3")
    (kind note)
    (seq 286)
    (text
     "Fixed a real bug found in graph.rkt's overrides-edge logic (T59) while building this fixture: base-member lookup matched the bare name against ANY def in the base file, picking whichever same-named method came first in file order, rather than a direct member of the specific base class. A 3-level chain (LoudDog : Dog : Animal) exposed it - LoudDog.Speak was wired to override Animal.Speak instead of its real direct parent Dog.Speak. Fixed by requiring the matched base-member's own scope to equal the base class's qualname.")
    (ts "2026-09-27T10:17:11Z"))
   ((agent "xl3")
    (checks (((cmd "raco test tests/cs-graph-test.rkt") (secs 0.3))))
    (kind done)
    (seq 287)
    (ts "2026-09-27T10:17:12Z")
    (verified #t)))))
