((id "T63")
 (title "C# extractor: implements the generic extract/resolve-import contract, no dotnet needed")
 (status open)
 (priority 2)
 (goal
  "A body walker over each cs-member's token range emits calls (M(, this.M(, base.M(, Type.M(, new T(, method-group refs) with arity, the type's base/interface list, attributes, `using`, declared namespaces, has-statements?, and field/parameter declared types for `declared` edges, per the graph-ir contract; resolve-import maps `using X` to files declaring X. This is the same six-function contract py-extract and rkt-extract implement - the generic engine is what makes this an exact, no-SDK C# graph, not a bespoke Roslyn integration (compare T55, which stays optional).")
 (after ("T59"))
 (checks ("raco test tests/cs-graph-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("graph"))
 (claimed-by #f)
 (created "2026-09-27T08:50:21Z")
 (updated "2026-09-27T08:50:21Z")
 (log ()))
