((id "T64")
 (title "Entry points: per-language preludes plug into one generic entry-resolution engine")
 (status open)
 (priority 1)
 (goal
  "Each language's entry-prelude and implicit-names (a short table of Datalog rules and implicit-call names) run before the user's own rules in one shared evaluator; Racket-computed facts (test_module/test_name/console_script/package_init/controller_base/public_api/api_module/root_module/has_statements) are generic helpers any language's prelude can call; `entry(\"path#S\").` facts and `steer: entry` markers work identically for every language; `steer rules entries` lists each entry with the admitting rule. Adding a language's entry heuristics later means adding its prelude table, not new engine code.")
 (after ("T61" "T62" "T63"))
 (checks ("raco test tests/entries-test.rkt"))
 (anchors (((hash "48d6efde5b20") (ref "steer/rules.rkt#check-rules"))))
 (touches ())
 (tags ("graph"))
 (claimed-by #f)
 (created "2026-09-27T08:50:21Z")
 (updated "2026-09-27T08:50:21Z")
 (log ()))
