((id "T64")
 (title "Entry points: per-language preludes plug into one generic entry-resolution engine")
 (status done)
 (priority 1)
 (goal
  "Each language's entry-prelude and implicit-names (a short table of Datalog rules and implicit-call names) run before the user's own rules in one shared evaluator; Racket-computed facts (test_module/test_name/console_script/package_init/controller_base/public_api/api_module/root_module/has_statements) are generic helpers any language's prelude can call; `entry(\"path#S\").` facts and `steer: entry` markers work identically for every language; `steer rules entries` lists each entry with the admitting rule. Adding a language's entry heuristics later means adding its prelude table, not new engine code.")
 (after ("T61" "T62" "T63"))
 (checks ("raco test tests/entries-test.rkt"))
 (anchors (((hash "48d6efde5b20") (ref "steer/rules.rkt#check-rules"))))
 (touches ())
 (tags ("graph"))
 (claimed-by "xl3")
 (created "2026-09-27T08:50:21Z")
 (updated "2026-09-27T10:31:26Z")
 (log
  (((agent "xl3")
    (kind note)
    (seq 289)
    (text
     "Extracted the Datalog evaluator (parse-rules/eval-datalog/run-datalog/tuples-of) out of rules.rkt into a new steer/datalog.rkt so entries.rkt could share it without a require cycle (rules.rkt -> entries.rkt -> datalog.rkt; rules.rkt also requires datalog.rkt directly and re-exports it, unchanged for existing callers). Also found and fixed a real cross-language leakage bug while testing this repo's own mixed tree: language-specific entry-prelude rules ran against the FULLY SHARED fact base with no language filter, so e.g. Racket top-level defines were satisfying Python's public_api+root_module rule and showing up 'admitted by python'. Fixed by adding a lang(ID, L) fact for every graph node and requiring every prelude rule to join on it.")
    (ts "2026-09-27T10:31:25Z"))
   ((agent "xl3")
    (checks (((cmd "raco test tests/entries-test.rkt") (secs 0.9))))
    (kind done)
    (seq 290)
    (ts "2026-09-27T10:31:26Z")
    (verified #t)))))
