((id "T65")
 (title "Reachability: reachable/dead facts, `steer rules dead`, `steer rules reach SYM`")
 (status done)
 (priority 1)
 (goal
  "Worklist BFS in Racket over the indexed graph (one generic algorithm, language-blind: it only walks gedge structs) with: forward over calls/refs/inherits/implements/imports/decorates/defines; symbol reachable => its module reachable => the module's imports and <toplevel>; class reachable => its constructors; overrides followed backwards from a reachable base. Asserted as reachable(S)/dead(S) facts. `rules dead` emits capped, root-cause-folded dead-symbol/dead-module warnings naming the two override mechanisms as the fix, with per-language confidence stats in detail; exit 1 when non-empty. `rules reach SYM` prints entries reaching SYM with a shortest path each, and what SYM reaches. A user rule may promote dead(S) to a violation (error, exit 1) through rules check.")
 (after ("T64"))
 (checks ("raco test tests/reach-test.rkt"))
 (anchors (((hash "9f5554713172") (ref "steer/rules.rkt#shortest-path"))))
 (touches ())
 (tags ("graph"))
 (claimed-by "xl3")
 (created "2026-09-27T08:50:21Z")
 (updated "2026-09-27T10:42:34Z")
 (log
  (((agent "xl3")
    (kind note)
    (seq 292)
    (text
     "Found and fixed two real bugs in the reachability walk while testing on the T60/T62/T63 fixtures and a purpose-built C# fixture: (1) graph.rkt's module->top-level-def 'defines' edges were walked forward, so a module becoming reachable (because ANY symbol in it was) made every OTHER top-level def in that file reachable too, defeating dead-code detection; (2) the same for class->member 'defines' edges - instantiating a class (e.g. 'new Widget()') made EVERY method on it reachable, not just its constructors. Fixed by only walking a 'defines' edge forward when its TARGET's kind is 'constructor - exactly and only 'class reachable => its constructors', nothing broader. Also found while writing the mutation test: a top-level Python function in a root module (nothing imports the file) is independently an entry via the public_api+root_module prelude rule regardless of whether anything calls it - by design (a library's public surface), but it means a naive mutation test using a plain non-underscore-prefixed helper name never goes dead; the test uses a leading-underscore name to isolate the call-based reachability it's actually testing.")
    (ts "2026-09-27T10:42:33Z"))
   ((agent "xl3")
    (checks (((cmd "raco test tests/reach-test.rkt") (secs 1.1))))
    (kind done)
    (seq 293)
    (ts "2026-09-27T10:42:34Z")
    (verified #t)))))
