((id "T65")
 (title "Reachability: reachable/dead facts, `steer rules dead`, `steer rules reach SYM`")
 (status open)
 (priority 1)
 (goal
  "Worklist BFS in Racket over the indexed graph (one generic algorithm, language-blind: it only walks gedge structs) with: forward over calls/refs/inherits/implements/imports/decorates/defines; symbol reachable => its module reachable => the module's imports and <toplevel>; class reachable => its constructors; overrides followed backwards from a reachable base. Asserted as reachable(S)/dead(S) facts. `rules dead` emits capped, root-cause-folded dead-symbol/dead-module warnings naming the two override mechanisms as the fix, with per-language confidence stats in detail; exit 1 when non-empty. `rules reach SYM` prints entries reaching SYM with a shortest path each, and what SYM reaches. A user rule may promote dead(S) to a violation (error, exit 1) through rules check.")
 (after ("T64"))
 (checks ("raco test tests/reach-test.rkt"))
 (anchors (((hash "9f5554713172") (ref "steer/rules.rkt#shortest-path"))))
 (touches ())
 (tags ("graph"))
 (claimed-by #f)
 (created "2026-09-27T08:50:21Z")
 (updated "2026-09-27T08:50:21Z")
 (log ()))
