((id "T66")
 (title "Per-file graph cache keyed by content hash, excluded from git")
 (status open)
 (priority 2)
 (goal
  ".steer/cache/graph/<lang>/<sha1>.rktd per file, one cache format shared by every language; a second run on an unchanged tree launches no worker and no scanner for any language (asserted by counting launches and wall time); steer init ignores .steer/cache/, steer doctor warns when it is tracked; cold <= 5s and warm <= 0.5s on a 500-file synthetic project, recorded in the test output.")
 (after ("T65"))
 (checks ("raco test tests/graph-cache-test.rkt"))
 (anchors (((hash "dfdf56f6d614") (ref "steer/store.rkt#init-store!"))))
 (touches ())
 (tags ("graph"))
 (claimed-by #f)
 (created "2026-09-27T08:50:21Z")
 (updated "2026-09-27T08:50:21Z")
 (log ()))
