((id "T69")
 (title "Language-aware docs for the graph: help, skill, README known limits")
 (status done)
 (priority 2)
 (goal
  "steer help rules|api and the steer-code skill say per language what is exact, declared, name-matched and invisible, how to declare an entry, and that dead findings are may-call over-approximations, from one shared coverage table (same pattern as T52); README known limits updated: rules is no longer Racket-only; dup still is; T55/T56 are now labelled optional precision upgrades, not requirements.")
 (after ("T65" "T67"))
 (checks ("raco test tests/skill-docs-test.rkt"))
 (anchors (((hash "c600320ef339") (ref "steer/main.rkt#commands"))))
 (touches ())
 (tags ("graph"))
 (claimed-by "xl3")
 (created "2026-09-27T08:50:21Z")
 (updated "2026-09-27T15:36:05Z")
 (log
  (((agent "xl3")
    (checks (((cmd "raco test tests/skill-docs-test.rkt") (secs 4.6))))
    (kind done)
    (seq 306)
    (ts "2026-09-27T15:36:05Z")
    (verified #t)))))
