((id "T7")
 (title "E1 failure-taxonomy logger: record attempts, tool feedback, outcomes; classify failures")
 (status done)
 (priority 1)
 (goal
  "Log every model attempt + tool output + result as rktd; classes: unbound-id, arity, syntax, idiom, semantic, timeout, tool-misuse. Drives what to build next.")
 (after ())
 (checks ("raco test tests/e1-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("measure"))
 (claimed-by "claude")
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T23:07:45Z")
 (log
  (((agent "claude")
    (kind note)
    (seq 142)
    (text
     "Built steer/failures.rkt: main.rkt logs every command's error/warning findings (and hook syntax errors) to gitignored .steer/failures.rktd, classified per note 04 (unbound-id, syntax, check-failed, tool-misuse, plan-error, drift, api-break, tool-failure). steer failures summarises and points at the catalog item for the largest class. Found a flag clash: global --agent vs a filter flag, so the filter is --who. Data is still empty of real model failures: needs agents using steer over time.")
    (ts "2026-09-26T23:07:39Z"))
   ((agent "claude")
    (checks (((cmd "raco test tests/e1-test.rkt") (secs 3.0))))
    (kind done)
    (seq 144)
    (ts "2026-09-26T23:07:45Z")
    (verified #t)))))
