((id "T7")
 (title "E1 failure-taxonomy logger: record attempts, tool feedback, outcomes; classify failures")
 (status open)
 (priority 1)
 (goal
  "Log every model attempt + tool output + result as rktd; classes: unbound-id, arity, syntax, idiom, semantic, timeout, tool-misuse. Drives what to build next.")
 (after ())
 (checks ("raco test tests/e1-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("measure"))
 (claimed-by #f)
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T06:14:34Z")
 (log ()))
