((id "T70")
 (title "XL3 · Code graph, entry points and reachability")
 (status done)
 (priority 1)
 (goal
  "End to end through the CLI on a Racket, a Python and a C# fixture project (no dotnet SDK; python3 only): rules check with layers on all three; rules entries lists heuristic and annotated entries; rules dead finds the planted dead symbol and nothing else; adding `# steer: entry` above it clears the finding; rules reach names the test that covers a symbol; api snapshot --entries then a signature change flows into api diff, which reports the break and the mismatched caller. One generic engine (graph.rkt + the six-function lang contract) drives every language listed - adding a new language later means implementing that contract, not new engine code. T57 (the narrower API-locks-and-clones milestone) and this milestone share T67/T69; T57 stays open for its clone-detection half (T18).")
 (after ("T58" "T59" "T60" "T61" "T62" "T63" "T64" "T65" "T66" "T67" "T68" "T69"))
 (checks ("raco test tests/graph-integration-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("graph" "milestone"))
 (claimed-by "xl3")
 (created "2026-09-27T08:51:35Z")
 (updated "2026-09-27T15:43:28Z")
 (log
  (((agent "xl3")
    (checks (((cmd "raco test tests/graph-integration-test.rkt") (secs 3.7))))
    (kind done)
    (seq 308)
    (ts "2026-09-27T15:43:28Z")
    (verified #t)))))
