((id "T72")
 (title "`steer vision show`: the read path, and its own help text")
 (status open)
 (priority 1)
 (goal
  "Prints the north star (if set) and the priority list ranked, each with its rationale on the next line if present; `--json` for the note-03 protocol like every other command. Empty state (`steer init` just ran, nothing set yet) prints a short one-line hint, not a blank/confusing output - matches `steer show ID`'s existing style for a task with no notes yet.")
 (after ("T71"))
 (checks ("raco test tests/vision-show-test.rkt"))
 (anchors (((hash "3d08587acc7f") (ref "steer/main.rkt#commands"))))
 (touches ())
 (tags ("vision"))
 (claimed-by #f)
 (github ((digest "913426ca62ee") (kind issue) (number 29)))
 (created "2026-09-27T18:12:49Z")
 (updated "2026-09-27T18:14:05Z")
 (log ()))
