((id "T73")
 (title "Fold vision into `resume`'s packet automatically")
 (status open)
 (priority 1)
 (goal
  "steer resume's budgeted packet gains a short vision section (north star + top few priorities) ahead of the active task, unmissable at session start the same way resume already makes active-task/stale-anchor state unmissable - this is the one continuity gap note 06's design didn't cover: tasks and code can drift from a PLAN (stale/rules already catch that), but nothing previously caught the plan's own GOALS drifting without anyone deciding they should. Budget: the packet's existing size ceiling (2 KB) is not relaxed - vision competes for the same budget as everything else in resume, trimmed first if priorities list is long.")
 (after ("T72"))
 (checks ("raco test tests/vision-resume-test.rkt"))
 (anchors (((hash "3eccceefd98b") (ref "steer/cmd-tasks.rkt#cmd-checkpoint"))))
 (touches ())
 (tags ("vision"))
 (claimed-by #f)
 (github ((digest "a3c7e4112f83") (kind issue) (number 31)))
 (created "2026-09-27T18:12:49Z")
 (updated "2026-09-27T18:14:06Z")
 (log ()))
