((id "T75")
 (title "Stretch: flag a task whose goal seems to conflict with a stated priority")
 (status open)
 (priority 3)
 (goal
  "Extends the same 'noticing tension' idea stale anchors already apply to code-vs-plan drift, now applied to plan-vs-goals drift: a cheap, explicitly heuristic check (word-overlap or an explicit #:conflicts-with marker on a task, not semantic understanding steer cannot honestly claim) that flags, as an info-level finding on `steer stale`/`steer list`, a task whose own goal text looks like it works against a stated priority. Labelled a hint, not a guarantee, the same honesty `~heuristic` anchors already use - false negatives are expected and fine; a false POSITIVE that gets ignored repeatedly is the failure mode to test against and avoid.")
 (after ("T73"))
 (checks ("raco test tests/vision-conflict-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("vision"))
 (claimed-by #f)
 (github ((digest "3d48d8383d97") (kind issue) (number 32)))
 (created "2026-09-27T18:12:49Z")
 (updated "2026-09-27T18:14:07Z")
 (log ()))
