((id "T77")
 (title "T70 follow-up: base-class name-match is kind-blind (notes/16 SS9)")
 (status done)
 (priority 2)
 (goal
  "Fix graph.rkt's inherits/implements resolution to filter the imported/global name-match fallback to type-like defs (class/struct/interface/enum) only, so a base-class reference with no in-project type match (e.g. C#'s : Attribute, unresolvable since System.Attribute is a BCL type) cannot bind to an unrelated same-bare-named property/field/method. Add a fixture pinning it (tests/fixtures/csproj/Helper.cs + tests/cs-graph-test.rkt). Document the fix plus a second, separate, left-open module-cascade issue (module-scoped decorates/calls bypass the constructor-only defines restriction) as notes/16 SS9, with cross-language measurement (0/0/0/97 on rebellion/tomli/aiofiles/GuardClauses).")
 (after ("T70"))
 (checks ("raco test tests/cs-graph-test.rkt" "raco test tests/graph-measure-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("graph"))
 (claimed-by "claude")
 (created "2026-09-27T18:34:02Z")
 (updated "2026-09-27T18:41:52Z")
 (log
  (((agent "claude")
    (kind note)
    (seq 312)
    (text
     "Two independent mechanisms, not one: (A) kind-blind base-class name-match, fixed here (graph.rkt bases loop, filtered to class/struct/interface/enum) - 97 bogus inherits(name-match) edges in GuardClauses, all onto one property, 0 in rebellion/tomli/aiofiles. (B) module-scoped decorates/calls edges bypass reach.rkt's constructor-only defines restriction - real, measured (8 false-negatives in GuardClauses), left open: needs a cross-extractor decorator-scoping change, not a filter.")
    (ts "2026-09-27T18:34:18Z"))
   ((agent "claude")
    (checks
     (((cmd "raco test tests/cs-graph-test.rkt") (secs 0.4))
      ((cmd "raco test tests/graph-measure-test.rkt") (secs 1.4))))
    (kind done)
    (seq 313)
    (ts "2026-09-27T18:34:24Z")
    (verified #t)))))
