((id "T78")
 (title
  "Module-scoped decorates/calls edges bypass reach.rkt's constructor-only defines restriction (notes/16 SS9, mechanism B)")
 (status open)
 (priority 6)
 (goal
  "reach.rkt's defines-edge-to-walk? deliberately restricts module->defines edges to constructor targets, so a reachable module doesn't light up every top-level class. But module->decorates/calls edges (from a decorator/call at file top level, or - per cs-extract.rkt's own enclosing-type-of returning #f for a top-level type - a type-level attribute on a TOP-LEVEL type) are walked unconditionally, bypassing that restriction entirely. Measured cost on GuardClauses: 4 classes + their 4 constructors (8 symbols) wrongly reachable via this path alone (notes/16 SS9 table). The fix is a scoping-convention change in BOTH csharp.rkt and python.rkt (scope a top-level def's own decorator ref to itself, not its enclosing/module scope) while preserving the existing member-level behavior the SS7/SS8 fixtures assert; cannot be patched from reach.rkt alone since a module-scoped calls ref from real top-level script code must stay walkable.")
 (after ("T77"))
 (checks ())
 (anchors ())
 (touches ())
 (tags ("graph"))
 (claimed-by #f)
 (created "2026-09-27T18:34:37Z")
 (updated "2026-09-27T18:41:52Z")
 (log ()))
