((id "T79")
 (title "C2-doc: cheap proxy read on whether steer doc helps the unbound-identifier failure class")
 (status done)
 (priority 2)
 (goal
  "Extend scripts/retry-eval.rkt with a c2-doc retry condition (steer doc exists NAME feedback in place of the raw compiler error) targeting the 10/50 C0 failures that are Racket's own unbound-identifier error - confirmed disjoint from A1's syntax-eligible subset. Reuses run1's existing turn-1 artifacts, no new C0 generation. Result: C1 20% vs C2-doc 50% (n=10, CIs overlap, monotonic win - never worse than C1, 3 net gains all mechanistically explained). Written to notes/07-baseline-results.md.")
 (after ("T9"))
 (checks ("test -f notes/07-baseline-results.md"))
 (anchors ())
 (touches ())
 (tags ("measure"))
 (claimed-by "claude")
 (created "2026-09-27T19:58:32Z")
 (updated "2026-09-27T19:58:39Z")
 (log
  (((agent "claude")
    (checks (((cmd "test -f notes/07-baseline-results.md") (secs 0.0))))
    (kind done)
    (seq 411)
    (ts "2026-09-27T19:58:39Z")
    (verified #t)))))
