((id "T8")
 (title "Assemble task sets T1-T3 (exercises, library use, repair) with a hold-out split")
 (status done)
 (priority 1)
 (goal
  "Note 04 task sets with hidden tests, fetched into gitignored samples/ from pinned sources (make samples). Newly written tasks are split out as their own task.")
 (after ())
 (checks ("racket scripts/samples.rkt status --require"))
 (anchors ())
 (touches ())
 (tags ("measure"))
 (claimed-by "claude")
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T07:26:32Z")
 (log
  (((agent "claude")
    (kind note)
    (seq 44)
    (text
     "Data under samples/ (gitignored), rebuilt by scripts/samples.rkt from pinned sources in scripts/samples-sources.rktd. T2 = exercism tasks whose reference uses ids exported by racket/list, racket/string, ... but not racket/base (a proxy for library use). T3 = seeded mutants (deleted closer; plausible-but-unbound name) of exercism references, kept only if they fail. Split by sha1 of the base exercise so mutants never cross the split. validate: 235/235 exercism tasks behave (refs pass, mutants fail).")
    (ts "2026-09-26T07:26:31Z"))
   ((agent "claude")
    (checks (((cmd "racket scripts/samples.rkt status --require") (secs 0.4))))
    (kind done)
    (seq 47)
    (ts "2026-09-26T07:26:32Z")
    (verified #t)))))
