((id "T8")
 (title "Assemble task sets T1-T3 (exercises, library use, repair) with a hold-out split")
 (status open)
 (priority 1)
 (goal
  "Note 04 task sets with hidden tests; include newly written tasks to limit training contamination.")
 (after ())
 (checks ("test -d eval/tasks && test -d eval/holdout"))
 (anchors ())
 (touches ())
 (tags ("measure"))
 (claimed-by #f)
 (created "2026-09-26T06:14:34Z")
 (updated "2026-09-26T06:14:34Z")
 (log ()))
