((id "T81")
 (title "H1 · function-length finding from existing def-line/def-end")
 (status open)
 (priority 2)
 (goal
  "graph.rkt's def struct already carries line/end per symbol across all three languages -\nthis is a `steer rules` finding, not a new extraction. Add a configurable LOC threshold (default ~50,\nliterature-typical) and report over-length functions/methods per language, reusing the existing graph,\nzero extractor changes.")
 (after ("T80"))
 (checks ("raco test tests/quality-length-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "5416b8b1caf7") (kind issue) (number 34)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:24Z")
 (log ()))
