((id "T82")
 (title "H2 · parameter-count finding from existing def-shape")
 (status open)
 (priority 2)
 (goal
  "def-shape already holds the rendered signature (\"Fetch(string, string, int)\") per language.\nParse parameter count from it (language-aware split - watch for generics/nested parens in C#, keyword\nargs in Python) and flag long-parameter-list per Fowler's threshold (~4-5). Zero new extraction.")
 (after ("T80"))
 (checks ("raco test tests/quality-params-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "68c273ba8432") (kind issue) (number 35)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:24Z")
 (log ()))
