((id "T83")
 (title "H3 · cyclomatic complexity per function (new per-language extraction)")
 (status open)
 (priority 2)
 (goal
  "Unlike H1/H2, this needs real extractor work: count branch tokens (if/cond/when/unless/and/or\nin Racket; if/elif/for/while/and/or/except/with in Python; if/for/while/case/&&/||/catch/?: in C#)\nper def during the SAME extraction pass that already builds file-facts, so the count travels with the\ndef like line/end/shape do. McCabe's formula (edges - nodes + 2, or branches + 1). Flag at McCabe's own\nliterature threshold (>10 warn, >20 flag hard).")
 (after ("T80"))
 (checks ("raco test tests/quality-complexity-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "8277ae1a6e63") (kind issue) (number 36)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:25Z")
 (log ()))
