((id "T84")
 (title "H4 · nesting depth / cognitive complexity")
 (status open)
 (priority 2)
 (goal
  "Reuses H3's branch-token scan but weights by NESTING depth (Campbell 2018's cognitive\ncomplexity), not just branch count - meant to catch the case cyclomatic complexity misses: a flat\nsequence of 15 independent ifs (annoying but readable) vs 4 nested ifs (worse, same cyclomatic count).\nReport both numbers side by side so a later eval can tell which one actually correlates with anything.")
 (after ("T83"))
 (checks ("raco test tests/quality-nesting-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "a22be98326f9") (kind issue) (number 40)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:27Z")
 (log ()))
