((id "T85")
 (title "H5 · magic number / literal detection")
 (status open)
 (priority 2)
 (goal
  "Flag unnamed numeric/string literals outside an allow-list (0, 1, -1, and the language's own\nidiomatic exceptions) appearing in a def's body, per language. Needs a literal-scanning pass per\nextractor; independent of H3/H4's branch-counting work.")
 (after ("T80"))
 (checks ("raco test tests/quality-magic-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "83743a42baa6") (kind issue) (number 37)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:25Z")
 (log ()))
