((id "T86")
 (title "H6 · global / mutable shared-state usage")
 (status open)
 (priority 2)
 (goal
  "The hardest of the six to define generically: 'global' means something different per language\n(Racket top-level define + set!, Python module-level assignment read via `global`, C# static mutable\nfields). Needs real per-language design before extraction, not just a token count - scope this task to\nproducing that design plus a first-cut implementation for ONE language, with the other two as explicit\nfollow-up scope, rather than pretending one shared definition covers all three cleanly.")
 (after ("T80"))
 (checks ("raco test tests/quality-globals-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "c51a2ba6ae3b") (kind issue) (number 38)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:26Z")
 (log ()))
