((id "T87")
 (title "H7 · evaluate wrapping lizard as a cross-check on H1/H3, native vs external")
 (status open)
 (priority 2)
 (goal
  "lizard computes LOC+cyclomatic complexity generically across a dozen languages from a\nlightweight tokenizer. Run it against the same fixtures/corpora H1/H3 already measure and diff the\nnumbers - where they disagree, that's either a bug in H3 or a real definitional difference (worth\ndocumenting either way, matching notes/12/16's own 'measure against real code' discipline). Decide:\nkeep native (consistent with steer's own graph, no new dependency) or adopt lizard's numbers for\ncross-language consistency (external dependency, proven multi-language accuracy). Write the decision\ndown, don't just leave both running forever.")
 (after ("T81" "T83"))
 (checks ())
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "4dfc81f60bce") (kind issue) (number 41)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:28Z")
 (log ()))
