((id "T88")
 (title "H8 · evaluate wrapping radon for Python's maintainability index")
 (status open)
 (priority 2)
 (goal
  "radon's maintainability index (Halstead volume + cyclomatic complexity + LOC, Python-only) is\na well-known composite score with no Racket/C# equivalent readily available. Decide whether a\nPython-only MI number is worth reporting asymmetrically (steer already tolerates per-language\nasymmetry - see notes/16 SS1's C# declared=0% finding) or whether it's confusing next to two languages\nthat don't have it.")
 (after ("T81"))
 (checks ())
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "c743b13405bd") (kind issue) (number 42)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:29Z")
 (log ()))
