((id "T89")
 (title "H9 · `steer rules quality` - the unified report surfacing H1-H6")
 (status open)
 (priority 2)
 (goal
  "One command, one report, configurable thresholds per finding kind, all three languages -\nthe shippable deliverable phases H1-H6 build toward. Follows the same shape as `steer rules dead`:\nfindings with source locations, not raw scores. This is what H10-H12's eval tasks actually feed to a\nmodel as retry/prompt text.")
 (after ("T81" "T82" "T83" "T84" "T85" "T86"))
 (checks ("raco test tests/quality-rules-test.rkt"))
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "a374f96e8f70") (kind issue) (number 43)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:29Z")
 (log ()))
