((id "T92")
 (title "H12 · Tier-3: prompt-conditioning (mention constraints up front, not as a retry)")
 (status open)
 (priority 2)
 (goal
  "The most natural fit for 'avoid magic numbers / deep nesting / long functions' is proactive\nguidance in the ORIGINAL prompt, not reactive repair after a failure - a C0-variant condition, not a\nretry condition. Compare first-attempt pass rate AND H9's quality findings on the SAME task set, plain\nprompt vs prompt-plus-constraints, to see whether naming the constraint helps, hurts (models sometimes\nget worse when overloaded with extra instructions), or does nothing to correctness while genuinely\nimproving quality.")
 (after ("T89"))
 (checks ())
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "87b232438bc3") (kind issue) (number 45)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:30Z")
 (log ()))
