((id "T93")
 (title "H13 · apply notes/04's decision rule to H10/H11/H12 individually")
 (status open)
 (priority 2)
 (goal
  "Same discipline T79/notes/07 already used for C2-doc: state each technique's measured effect\nsize, confidence interval, and sample size plainly, and say go/no-go per notes/04's rule (keep if it\nclears noise without raising false-positive harm; drop or redesign otherwise) BEFORE combining anything.\nDo not average incomparable outcome variables (H10 is pass/fail like C1/C2-doc; H11/H12 also touch a\nquality score) into one number - report them as the different kinds of finding they are.")
 (after ("T90" "T91" "T92"))
 (checks ())
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "20fd6c1bd7d2") (kind issue) (number 46)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:31Z")
 (log ()))
