((id "T94")
 (title "H14 · combined condition: stack whichever techniques individually cleared H13's bar")
 (status open)
 (priority 2)
 (goal
  "Only for techniques H13 marked keep: build ONE condition combining them (e.g. doc-search +\ndead-code feedback together, if both individually helped) and test on the union of their eligible\nsubsets. The real question this answers: additive (effects stack), synergistic (combined > sum of\nparts), or redundant (combined ~= the stronger one alone, the weaker one added nothing once the other\nwas present). If zero techniques clear H13's bar, this task is a no-op by construction and should be\ndropped, not forced.")
 (after ("T93"))
 (checks ())
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "54f11b25cb54") (kind issue) (number 47)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:32Z")
 (log ()))
