((id "T95")
 (title "F9 done · code-quality metrics measured, not assumed")
 (status open)
 (priority 2)
 (goal
  "Milestone close: every H-series metric is either shipped (native or wrapped-tool decision\nmade in H7/H8) and, where a Tier-3 experiment applies to it at all, measured with a stated verdict\n(H13) rather than left as an unvalidated [hyp] tag the way F1-F8 mostly still are. Update notes/02's\ncatalog entry and notes/06's [hyp] tags for whichever of these graduate to [tested].")
 (after ("T87" "T88" "T94"))
 (checks ())
 (anchors ())
 (touches ())
 (tags ("quality"))
 (claimed-by #f)
 (github ((digest "3417844c9afc") (kind issue) (number 48)))
 (created "2026-09-27T21:47:52Z")
 (updated "2026-09-27T21:48:32Z")
 (log ()))
